// This code was generated by codegen/main.go. DO NOT EDIT.
//
// Runtime schemas for the types in ./types.ts. Optional fields use .nullish()
// because Go marshals a nil pointer, slice or map as null rather than omitting
// the key, and objects are loose so fields the generator does not know about are
// preserved rather than stripped.

import { z } from "zod"

/** anilist.MediaListStatus — status.go */
export const AL_MediaListStatusValues = ["CURRENT", "PLANNING"] as const
export const AL_MediaListStatusSchema = z.enum(AL_MediaListStatusValues)

