// This code was generated by codegen/main.go. DO NOT EDIT.
//
// Request body schemas, and the lookup used to find a response schema for a
// request that has already had its path parameters substituted.

import { z } from "zod"
import * as s from "./schemas"

//////////////////////////////////////////////////////////////////////////////////////////////////////
// Request bodies
//////////////////////////////////////////////////////////////////////////////////////////////////////

export const GetThing_VariablesSchema = z.looseObject({
    id: z.number(),
})

export const SaveThing_VariablesSchema = z.looseObject({
    name: z.string(),
    count: z.number().nullish(),
})

//////////////////////////////////////////////////////////////////////////////////////////////////////
// Response schemas
//////////////////////////////////////////////////////////////////////////////////////////////////////

export const responseSchemasByKey: Record<string, z.ZodType> = {
    "THINGS-get-thing": s.Models_ThingSchema,
    "THINGS-save-thing": z.boolean(),
}

/** Keyed by `${method} ${path}` for endpoints with no path parameters. */
export const staticEndpointSchemas: Record<string, { key: string, schema: z.ZodType }> = {
    "POST /api/v1/thing": { key: "THINGS-save-thing", schema: z.boolean() },
}

/** For endpoints with path parameters, matched against the concrete path. */
export const patternEndpointSchemas: ReadonlyArray<{
    method: string
    pattern: RegExp
    key: string
    schema: z.ZodType
}> = [
    { method: "GET", pattern: /^\/api\/v1\/thing\/[^\/]+$/, key: "THINGS-get-thing", schema: s.Models_ThingSchema },
]
