package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	typescriptFileName = "types.ts"
)

// GenerateTypescriptFile generates a Typescript file containing the types for the API routes parameters and responses based on the Docs struct.
func GenerateTypescriptFile(docsFilePath string, publicStructsFilePath string, outDir string, goStructStrs []string) error {

	handlers, err := LoadHandlers(docsFilePath)
	if err != nil {
		return err
	}

	goStructs, err := LoadPublicStructs(publicStructsFilePath)
	if err != nil {
		return err
	}

	selected, err := selectReferencedStructs(handlers, goStructs, goStructStrs)
	if err != nil {
		return err
	}

	// Create the typescript file
	if err := os.MkdirAll(outDir, os.ModePerm); err != nil {
		return fmt.Errorf("creating %s: %w", outDir, err)
	}
	outPath := filepath.Join(outDir, typescriptFileName)
	osFile, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("creating %s: %w", outPath, err)
	}
	defer osFile.Close()
	file := newErrWriter(osFile)

	// Write the typescript file
	file.WriteString("// This code was generated by codegen/main.go. DO NOT EDIT.\n\n")

	// Keep track of written Typescript types
	// This is to avoid name collisions
	writtenTypes := make(map[string]*GoStruct)

	file.WriteString("export type Nullish<T> = T | null | undefined\n\n")

	for _, pkg := range selected.Packages {

		file.WriteString("//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////\n")
		file.WriteString(fmt.Sprintf("// %s\n", formatPackageHeading(pkg)))
		file.WriteString("//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////\n\n")

		for _, goStruct := range selected.ByPackage[pkg] {

			writeTypescriptType(file, goStruct, writtenTypes)

		}

	}

	//for _, goStruct := range referencedStructs {
	//
	//	writeTypescriptType(file, goStruct, writtenTypes)
	//
	//}

	return file.Err()
}

// getReferencedStructsRecursively returns a map of GoStructs that are referenced by the fields of sharedStructs and otherStructs.
func getReferencedStructsRecursively(sharedStructs, otherStructs []*GoStruct, goStructsMap map[string]*GoStruct) (map[string]*GoStruct, bool) {
	allStructs := make(map[string]*GoStruct)
	for _, sharedStruct := range sharedStructs {
		allStructs[sharedStruct.Package+"."+sharedStruct.Name] = sharedStruct
	}
	for _, otherStruct := range otherStructs {
		allStructs[otherStruct.Package+"."+otherStruct.Name] = otherStruct
	}

	// Keep track of the structs that have been visited

	referencedStructs := make(map[string]*GoStruct)

	for _, strct := range allStructs {
		getReferencedStructs(strct, referencedStructs, goStructsMap)
	}

	return referencedStructs, true
}

func getReferencedStructs(goStruct *GoStruct, referencedStructs map[string]*GoStruct, goStructsMap map[string]*GoStruct) {
	if _, ok := referencedStructs[goStruct.Package+"."+goStruct.Name]; ok {
		return
	}
	referencedStructs[goStruct.Package+"."+goStruct.Name] = goStruct
	for _, field := range goStruct.Fields {
		if field.UsedStructType != "" {
			if usedStruct, ok := goStructsMap[field.UsedStructType]; ok {
				getReferencedStructs(usedStruct, referencedStructs, goStructsMap)
			}
		}
	}
	if goStruct.AliasOf != nil {
		if usedStruct, ok := goStructsMap[goStruct.AliasOf.UsedStructType]; ok {
			getReferencedStructs(usedStruct, referencedStructs, goStructsMap)
		}
	}
}

func writeTypescriptType(f *errWriter, goStruct *GoStruct, writtenTypes map[string]*GoStruct) {
	f.WriteString("/**\n")
	f.WriteString(fmt.Sprintf(" * - Filepath: %s\n", strings.TrimPrefix(goStruct.Filepath, "../")))
	f.WriteString(fmt.Sprintf(" * - Filename: %s\n", goStruct.Filename))
	f.WriteString(fmt.Sprintf(" * - Package: %s\n", goStruct.Package))
	if len(goStruct.Comments) > 0 {
		f.WriteString(fmt.Sprintf(" * @description\n"))
		for _, cmt := range goStruct.Comments {
			f.WriteString(fmt.Sprintf(" *  %s\n", strings.TrimSpace(cmt)))
		}
	}
	f.WriteString(" */\n")

	if len(goStruct.Fields) > 0 {
		f.WriteString(fmt.Sprintf("export type %s = {\n", goStruct.FormattedName))
		for _, field := range goStruct.Fields {
			if field.JsonName == "" {
				continue
			}
			fieldNameSuffix := ""
			if !field.Required {
				fieldNameSuffix = "?"
			}

			if len(field.Comments) > 0 {
				f.WriteString(fmt.Sprintf("    /**\n"))
				for _, cmt := range field.Comments {
					f.WriteString(fmt.Sprintf("     * %s\n", strings.TrimSpace(cmt)))
				}
				f.WriteString(fmt.Sprintf("     */\n"))
			}

			typeText := field.TypescriptType
			typeText = strings.ReplaceAll(typeText, "RawMessage", "Record<string, any>")
			//if !field.Required {
			//	switch typeText {
			//	case "string", "number", "boolean":
			//	default:
			//		typeText = "Nullish<" + typeText + ">"
			//	}
			//}

			f.WriteString(fmt.Sprintf("    %s%s: %s\n", field.JsonName, fieldNameSuffix, typeText))
		}
		f.WriteString("}\n\n")
	}

	if goStruct.AliasOf != nil {
		if goStruct.AliasOf.DeclaredValues != nil && len(goStruct.AliasOf.DeclaredValues) > 0 {
			union := ""
			if len(goStruct.AliasOf.DeclaredValues) > 5 {
				union = strings.Join(goStruct.AliasOf.DeclaredValues, " |\n    ")
			} else {
				union = strings.Join(goStruct.AliasOf.DeclaredValues, " | ")
			}
			f.WriteString(fmt.Sprintf("export type %s = %s\n\n", goStruct.FormattedName, union))
		} else {
			f.WriteString(fmt.Sprintf("export type %s = %s\n\n", goStruct.FormattedName, goStruct.AliasOf.TypescriptType))
		}
	}

	// Add the struct to the written types
	writtenTypes[goStruct.Package+"."+goStruct.Name] = goStruct
}

func getUnformattedGoType(goType string) string {
	if strings.HasPrefix(goType, "[]") {
		return getUnformattedGoType(goType[2:])
	}

	if strings.HasPrefix(goType, "*") {
		return getUnformattedGoType(goType[1:])
	}

	if strings.HasPrefix(goType, "map[") {
		s := strings.TrimPrefix(goType, "map[")
		value := ""
		for i, c := range s {
			if c == ']' {
				value = s[i+1:]
				break
			}
		}
		return getUnformattedGoType(value)
	}

	return goType
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
