package codegen

import (
	"cmp"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// routeSchema is one endpoint's contract, as needed by the generated lookups.
type routeSchema struct {
	Key            string // e.g. "ANILIST-get-anime-collection"
	Method         string // e.g. "GET"
	Endpoint       string // e.g. "/api/v1/anime-entries/{id}"
	ResponseSchema string // a zod expression, qualified into the schemas module
	VariablesName  string // e.g. "GetAnimeEntry_Variables", or "" when the route takes none
}

// collectRouteSchemas flattens the handlers into one entry per (route, method),
// in a deterministic order.
//
// Routes with no methods are skipped: they are not reachable over HTTP and
// GenerateTypescriptEndpointsFile omits them too.
func collectRouteSchemas(handlers []*RouteHandler) []*routeSchema {
	routes := make([]*routeSchema, 0, len(handlers))

	for _, handler := range handlers {
		if handler.Api == nil || len(handler.Api.Methods) == 0 {
			continue
		}

		groupName := strings.ToUpper(strings.TrimSuffix(handler.Filename, ".go"))
		trimmedName := strings.TrimPrefix(handler.Name, "Handle")

		variablesName := ""
		if len(handler.Api.Params) > 0 || len(handler.Api.BodyFields) > 0 {
			variablesName = trimmedName + "_Variables"
		}

		for _, method := range handler.Api.Methods {
			routes = append(routes, &routeSchema{
				Key:            getEndpointKey(handler.Name, groupName),
				Method:         method,
				Endpoint:       handler.Api.Endpoint,
				ResponseSchema: tsTypeToZodRef(handler.Api.ReturnTypescriptType, zodSchemasNamespace),
				VariablesName:  variablesName,
			})
		}
	}

	slices.SortStableFunc(routes, func(i, j *routeSchema) int {
		if c := cmp.Compare(i.Endpoint, j.Endpoint); c != 0 {
			return c
		}
		if c := cmp.Compare(i.Method, j.Method); c != 0 {
			return c
		}
		return cmp.Compare(i.Key, j.Key)
	})

	return routes
}

func writeZodEndpointSchemasFile(handlers []*RouteHandler, generated map[string]bool, outDir string) error {
	outPath := filepath.Join(outDir, zodEndpointSchemasFileName)
	osFile, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("creating %s: %w", outPath, err)
	}
	defer osFile.Close()
	f := newErrWriter(osFile)

	routes := collectRouteSchemas(handlers)

	f.WriteString("// This code was generated by codegen/main.go. DO NOT EDIT.\n")
	f.WriteString("//\n")
	f.WriteString("// Request body schemas, and the lookup used to find a response schema for a\n")
	f.WriteString("// request that has already had its path parameters substituted.\n\n")
	f.WriteString(`import { z } from "zod"` + "\n")
	f.Printf("import * as %s from \"./%s\"\n\n", zodSchemasNamespace, strings.TrimSuffix(zodSchemasFileName, ".ts"))

	writeVariablesSchemas(f, handlers, generated)
	writeEndpointLookups(f, routes, generated)

	return f.Err()
}

// writeVariablesSchemas emits a schema per request-body type.
//
// Mirrors endpoint.types.ts exactly, including its rule that body fields win over
// path params when a route declares both, so the schema names line up with the
// generated *_Variables types.
func writeVariablesSchemas(f *errWriter, handlers []*RouteHandler, generated map[string]bool) {
	sorted := make([]*RouteHandler, 0, len(handlers))
	for _, handler := range handlers {
		if handler.Api == nil || len(handler.Api.Methods) == 0 {
			continue
		}
		if len(handler.Api.Params) == 0 && len(handler.Api.BodyFields) == 0 {
			continue
		}
		sorted = append(sorted, handler)
	}
	slices.SortStableFunc(sorted, func(i, j *RouteHandler) int {
		return cmp.Compare(i.Name, j.Name)
	})

	f.WriteString("//////////////////////////////////////////////////////////////////////////////////////////////////////\n")
	f.WriteString("// Request bodies\n")
	f.WriteString("//////////////////////////////////////////////////////////////////////////////////////////////////////\n\n")

	for _, handler := range sorted {
		name := strings.TrimPrefix(handler.Name, "Handle") + "_Variables" + zodSchemaSuffix

		params := handler.Api.BodyFields
		if len(params) == 0 {
			params = handler.Api.Params
		}

		f.Printf("export const %s = z.looseObject({\n", name)
		for _, param := range params {
			if param.JsonName == "" {
				continue
			}
			f.Printf("    %s: %s,\n", quoteJSKey(param.JsonName), resolvable(paramSchema(param, zodSchemasNamespace), generated))
		}
		f.WriteString("})\n\n")
	}
}

// writeEndpointLookups emits the two tables probeResponseContract consults.
//
// Two tables rather than one because the overwhelming majority of endpoints are
// literal paths that can be found by an exact map lookup, and only a handful carry
// {placeholders} that are substituted before the request is sent and therefore have
// to be matched by pattern.
func writeEndpointLookups(f *errWriter, routes []*routeSchema, generated map[string]bool) {
	// A (method, endpoint) pair declared by two handlers is ambiguous: there is no
	// way to know which response schema applies. Omit those rather than guess.
	count := make(map[string]int, len(routes))
	for _, route := range routes {
		count[route.Method+" "+route.Endpoint]++
	}

	ambiguous := make([]string, 0)
	for lookup, n := range count {
		if n > 1 {
			ambiguous = append(ambiguous, lookup)
		}
	}
	slices.Sort(ambiguous)

	f.WriteString("//////////////////////////////////////////////////////////////////////////////////////////////////////\n")
	f.WriteString("// Response schemas\n")
	f.WriteString("//////////////////////////////////////////////////////////////////////////////////////////////////////\n\n")

	if len(ambiguous) > 0 {
		f.WriteString("// Omitted as ambiguous — more than one handler declares these, so which response\n")
		f.WriteString("// schema applies cannot be determined:\n")
		for _, lookup := range ambiguous {
			f.Printf("//   %s\n", lookup)
		}
		f.WriteString("\n")
		fmt.Printf("codegen: %d endpoint(s) declared more than once, omitted from the response schema lookup:\n", len(ambiguous))
		for _, lookup := range ambiguous {
			fmt.Printf("  %s\n", lookup)
		}
	}

	// Keyed by endpoint key, for callers that know it.
	f.WriteString("export const responseSchemasByKey: Record<string, z.ZodType> = {\n")
	byKey := make([]*routeSchema, 0, len(routes))
	for _, route := range routes {
		if count[route.Method+" "+route.Endpoint] > 1 {
			continue
		}
		byKey = append(byKey, route)
	}
	slices.SortStableFunc(byKey, func(i, j *routeSchema) int { return cmp.Compare(i.Key, j.Key) })
	emittedKey := make(map[string]bool, len(byKey))
	for _, route := range byKey {
		if emittedKey[route.Key] {
			continue
		}
		emittedKey[route.Key] = true
		f.Printf("    %s: %s,\n", quoteJSKey(route.Key), resolvable(route.ResponseSchema, generated))
	}
	f.WriteString("}\n\n")

	// Exact matches: "METHOD /literal/path".
	f.WriteString("/** Keyed by `${method} ${path}` for endpoints with no path parameters. */\n")
	f.WriteString("export const staticEndpointSchemas: Record<string, { key: string, schema: z.ZodType }> = {\n")
	for _, route := range routes {
		if strings.Contains(route.Endpoint, "{") || count[route.Method+" "+route.Endpoint] > 1 {
			continue
		}
		f.Printf("    %s: { key: %s, schema: %s },\n",
			quoteJSKey(route.Method+" "+route.Endpoint), jsStringLiteral(route.Key), resolvable(route.ResponseSchema, generated))
	}
	f.WriteString("}\n\n")

	// Pattern matches, for endpoints whose {placeholders} are substituted before the
	// request is made.
	f.WriteString("/** For endpoints with path parameters, matched against the concrete path. */\n")
	f.WriteString("export const patternEndpointSchemas: ReadonlyArray<{\n")
	f.WriteString("    method: string\n")
	f.WriteString("    pattern: RegExp\n")
	f.WriteString("    key: string\n")
	f.WriteString("    schema: z.ZodType\n")
	f.WriteString("}> = [\n")
	for _, route := range routes {
		if !strings.Contains(route.Endpoint, "{") || count[route.Method+" "+route.Endpoint] > 1 {
			continue
		}
		f.Printf("    { method: %s, pattern: %s, key: %s, schema: %s },\n",
			jsStringLiteral(route.Method), endpointPattern(route.Endpoint), jsStringLiteral(route.Key), resolvable(route.ResponseSchema, generated))
	}
	f.WriteString("]\n")
}

// resolvable returns expr unless it refers to a schema that was never generated, in
// which case it degrades to z.unknown().
//
// A handler can return a type that reaches no struct in the selected set -- types.ts
// does not declare it either -- and referencing its schema would not compile. Leaving
// that one endpoint unvalidated is the right trade: the alternative is a generated file
// that does not build.
func resolvable(expr string, generated map[string]bool) string {
	for _, ref := range referencedSchemaNames(expr) {
		if !generated[ref] {
			return zodUnknown
		}
	}
	return expr
}

// endpointPattern renders a JavaScript regex literal matching an endpoint template
// with its {placeholders} substituted.
//
// A placeholder matches one path segment; it is not allowed to span a "/", so
// /a/{id} cannot swallow /a/b/c and be mistaken for a different route.
func endpointPattern(endpoint string) string {
	var sb strings.Builder
	sb.WriteString("/^")

	for _, segment := range strings.Split(endpoint, "/") {
		if segment == "" {
			continue
		}
		sb.WriteString("\\/")
		if strings.HasPrefix(segment, "{") && strings.HasSuffix(segment, "}") {
			sb.WriteString("[^\\/]+")
			continue
		}
		sb.WriteString(escapeRegexLiteral(segment))
	}

	sb.WriteString("$/")
	return sb.String()
}

// escapeRegexLiteral escapes the characters that are special inside a JavaScript
// regex literal.
func escapeRegexLiteral(s string) string {
	var sb strings.Builder
	for _, r := range s {
		if strings.ContainsRune(`\^$.|?*+()[]{}/`, r) {
			sb.WriteRune('\\')
		}
		sb.WriteRune(r)
	}
	return sb.String()
}

//////////////////////////////////////////////////////////////////////////////////////////////////////
// schemas.assert.ts
//////////////////////////////////////////////////////////////////////////////////////////////////////

// writeZodAssertFile emits type-only assertions that each schema declares exactly
// the fields its TypeScript type does.
//
// The comparison is on the schema's .shape rather than on z.infer, because a loose
// object's inferred type carries an index signature that widens keyof to string —
// which would make the assertion vacuous.
//
// Key sets, not full types: an optional field's schema is .nullish(), so it infers
// X | null | undefined against the type's X | undefined. Comparing key sets catches
// the drift that actually happens (a field added, removed or renamed on a Go
// struct) without fighting that mismatch.
func writeZodAssertFile(selected *selectedStructs, outDir string) error {
	outPath := filepath.Join(outDir, zodAssertFileName)
	osFile, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("creating %s: %w", outPath, err)
	}
	defer osFile.Close()
	f := newErrWriter(osFile)

	f.WriteString("// This code was generated by codegen/main.go. DO NOT EDIT.\n")
	f.WriteString("//\n")
	f.WriteString("// Compile-time proof that ./schemas.ts and ./types.ts agree. This file has no\n")
	f.WriteString("// runtime output; it exists so that `npm run typecheck` fails when a schema and\n")
	f.WriteString("// its type disagree about which fields exist.\n\n")
	f.WriteString(`import type * as T from "./types"` + "\n")
	f.Printf("import * as %s from \"./%s\"\n\n", zodSchemasNamespace, strings.TrimSuffix(zodSchemasFileName, ".ts"))
	f.WriteString("/** Resolves to true only when A and B are the same type, otherwise to never. */\n")
	f.WriteString("type Exact<A, B> = [A] extends [B] ? ([B] extends [A] ? true : never) : never\n\n")

	for _, goStruct := range selected.All() {
		// Only object schemas have a .shape to compare. Enums and aliases have no
		// field set, so there is nothing to drift.
		if len(goStruct.Fields) == 0 {
			continue
		}
		if !hasSerializedField(goStruct) {
			continue
		}

		name := goStruct.FormattedName
		f.Printf("const _%s: Exact<keyof typeof %s.%s%s.shape, keyof T.%s> = true\n",
			name, zodSchemasNamespace, name, zodSchemaSuffix, name)
	}

	return f.Err()
}

// hasSerializedField reports whether any field reaches JSON. A struct whose every
// field is json:"-" emits an empty object schema and no TypeScript body, so there
// is nothing to assert.
func hasSerializedField(goStruct *GoStruct) bool {
	for _, field := range goStruct.Fields {
		if field.JsonName != "" {
			return true
		}
	}
	return false
}
