package codegen

import (
	"cmp"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

const (
	zodSchemasFileName         = "schemas.ts"
	zodEndpointSchemasFileName = "endpoint.schemas.ts"
	zodAssertFileName          = "schemas.assert.ts"

	// The namespace endpoint.schemas.ts imports schemas.ts under, rather than
	// listing several hundred named imports.
	zodSchemasNamespace = "s"
)

// GenerateZodSchemasFile generates runtime zod schemas for the same types that
// GenerateTypescriptFile declares as TypeScript types.
//
// Three files:
//
//   - schemas.ts          one schema per generated type, plus enum value arrays
//   - endpoint.schemas.ts request body schemas and the endpoint -> response schema lookup
//   - schemas.assert.ts   type-only assertions that each schema matches its type
//
// It reuses selectReferencedStructs, so the set of types here is by construction
// the set types.ts declares. If the two ever disagree, schemas.assert.ts stops
// compiling, which is the point.
func GenerateZodSchemasFile(handlersJsonPath string, structsJsonPath string, outDir string, goStructStrs []string) error {
	handlers, err := LoadHandlers(handlersJsonPath)
	if err != nil {
		return err
	}

	goStructs, err := LoadPublicStructs(structsJsonPath)
	if err != nil {
		return err
	}

	selected, err := selectReferencedStructs(handlers, goStructs, goStructStrs)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(outDir, os.ModePerm); err != nil {
		return fmt.Errorf("creating %s: %w", outDir, err)
	}

	if err := writeZodSchemasFile(selected, outDir); err != nil {
		return err
	}
	if err := writeZodEndpointSchemasFile(handlers, generatedSchemaNames(selected), outDir); err != nil {
		return err
	}
	return writeZodAssertFile(selected, outDir)
}

//////////////////////////////////////////////////////////////////////////////////////////////////////
// schemas.ts
//////////////////////////////////////////////////////////////////////////////////////////////////////

func writeZodSchemasFile(selected *selectedStructs, outDir string) error {
	order, backEdges, err := zodEmissionOrder(selected)
	if err != nil {
		return err
	}

	outPath := filepath.Join(outDir, zodSchemasFileName)
	osFile, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("creating %s: %w", outPath, err)
	}
	defer osFile.Close()
	f := newErrWriter(osFile)

	f.WriteString("// This code was generated by codegen/main.go. DO NOT EDIT.\n")
	f.WriteString("//\n")
	f.WriteString("// Runtime schemas for the types in ./types.ts. Optional fields use .nullish()\n")
	f.WriteString("// because Go marshals a nil pointer, slice or map as null rather than omitting\n")
	f.WriteString("// the key, and objects are loose so fields the generator does not know about are\n")
	f.WriteString("// preserved rather than stripped.\n\n")
	f.WriteString(`import { z } from "zod"` + "\n\n")

	for _, goStruct := range order {
		writeZodSchema(f, goStruct, backEdges[goStruct.FormattedName])
	}

	return f.Err()
}

// writeZodSchema emits one schema. lazyRefs names the referenced types that must
// be emitted as getters because they close a dependency cycle.
func writeZodSchema(f *errWriter, goStruct *GoStruct, lazyRefs map[string]bool) {
	name := goStruct.FormattedName + zodSchemaSuffix

	f.Printf("/** %s.%s — %s */\n", goStruct.Package, goStruct.Name, goStruct.Filename)

	// A string alias with declared constants becomes an enum, plus a values array
	// so the UI can build option lists from it instead of hardcoding them.
	if goStruct.AliasOf != nil && len(goStruct.AliasOf.DeclaredValues) > 0 {
		values := strings.Join(goStruct.AliasOf.DeclaredValues, ", ")
		f.Printf("export const %sValues = [%s] as const\n", goStruct.FormattedName, values)
		f.Printf("export const %s = z.enum(%sValues)\n\n", name, goStruct.FormattedName)
		return
	}

	if len(goStruct.Fields) > 0 {
		f.Printf("export const %s = z.looseObject({\n", name)
		for _, field := range goStruct.Fields {
			if field.JsonName == "" {
				// Not serialized (json:"-"), so it never appears in a payload.
				continue
			}
			expr := fieldSchema(field)
			if referencesAny(expr, lazyRefs) {
				// A getter defers resolution, which is how zod 4 expresses a
				// recursive schema.
				f.Printf("    get %s() { return %s },\n", quoteJSKeyForGetter(field.JsonName), expr)
				continue
			}
			f.Printf("    %s: %s,\n", quoteJSKey(field.JsonName), expr)
		}
		f.WriteString("})\n\n")
		return
	}

	if goStruct.AliasOf != nil {
		f.Printf("export const %s = %s\n\n", name, tsTypeToZod(goStruct.AliasOf.TypescriptType))
		return
	}

	// No fields and no alias: an empty struct still has to exist, since other
	// schemas reference it.
	f.Printf("export const %s = z.looseObject({})\n\n", name)
}

// referencesAny reports whether a rendered expression refers to any of the given
// schema identifiers.
func referencesAny(expr string, schemaNames map[string]bool) bool {
	if len(schemaNames) == 0 {
		return false
	}
	for _, ref := range referencedSchemaNames(expr) {
		if schemaNames[ref] {
			return true
		}
	}
	return false
}

// quoteJSKeyForGetter renders a getter name. A getter cannot use a quoted key the
// way a plain property can, so a name that is not a bare identifier is emitted in
// brackets as a computed getter.
func quoteJSKeyForGetter(name string) string {
	if isSafeJSIdentifier(name) && name != "" {
		return name
	}
	return "[" + quoteJSKey(name) + "]"
}

//////////////////////////////////////////////////////////////////////////////////////////////////////
// Emission order
//////////////////////////////////////////////////////////////////////////////////////////////////////

func structKey(goStruct *GoStruct) string {
	return goStruct.Package + "." + goStruct.Name
}

// generatedSchemaNames is the set of schema identifiers schemas.ts declares.
func generatedSchemaNames(selected *selectedStructs) map[string]bool {
	names := make(map[string]bool, len(selected.ByKey))
	for _, goStruct := range selected.All() {
		names[goStruct.FormattedName+zodSchemaSuffix] = true
	}
	return names
}

// zodEmissionOrder topologically sorts the selected structs so that no schema
// references a const declared later in the file.
//
// The graph is built from the SCHEMA IDENTIFIERS each struct's rendered expressions
// refer to, not from the Go types its fields point at. Those differ: two packages
// can share a type-name prefix ("habari" and "vendor_habari" both render as
// "Habari_"), so a field pointing at a Go type outside the selected set can still
// emit a reference to a schema inside it. The rendered text is what the file
// contains, so it is the only sound basis for ordering.
//
// Where a cycle makes ordering impossible, the schema names that close the cycle are
// reported in backEdges and the emitter renders those properties as getters. Only one
// type is self-referential today (LibraryExplorer_FileTreeNodeJSON), but cycles are
// detected generally so a new one keeps working.
//
// Returns an error on a duplicate schema name: two selected structs formatting to the
// same TypeScript name would declare the same const twice, which is a compile error in
// the generated file. types.ts has the same constraint, so this cannot happen today --
// but it should fail loudly rather than emit broken code if it starts to.
func zodEmissionOrder(selected *selectedStructs) (order []*GoStruct, backEdges map[string]map[string]bool, err error) {
	all := selected.All()

	byName := make(map[string]*GoStruct, len(all))
	for _, goStruct := range all {
		if prev, ok := byName[goStruct.FormattedName]; ok {
			return nil, nil, fmt.Errorf(
				"duplicate generated type name %q (from %s and %s): schemas.ts would declare the same const twice",
				goStruct.FormattedName, structKey(prev), structKey(goStruct))
		}
		byName[goStruct.FormattedName] = goStruct
	}

	const (
		white = 0
		grey  = 1
		black = 2
	)
	color := make(map[string]int, len(all))
	backEdges = make(map[string]map[string]bool)
	order = make([]*GoStruct, 0, len(all))

	var visit func(goStruct *GoStruct)
	visit = func(goStruct *GoStruct) {
		name := goStruct.FormattedName
		color[name] = grey

		for _, depName := range dependencySchemaNames(goStruct, byName) {
			switch color[depName] {
			case grey:
				// Cycle: this reference has to be deferred to a getter.
				if backEdges[name] == nil {
					backEdges[name] = make(map[string]bool)
				}
				backEdges[name][depName+zodSchemaSuffix] = true
			case white:
				visit(byName[depName])
			}
		}

		color[name] = black
		order = append(order, goStruct)
	}

	// Iterate in the already-sorted order so emission is deterministic.
	for _, goStruct := range all {
		if color[goStruct.FormattedName] == white {
			visit(goStruct)
		}
	}

	return order, backEdges, nil
}

// dependencySchemaNames returns the FormattedNames of the selected structs whose
// schemas goStruct's own schema refers to, sorted for determinism.
func dependencySchemaNames(goStruct *GoStruct, byName map[string]*GoStruct) []string {
	deps := make([]string, 0, len(goStruct.Fields))
	seen := make(map[string]bool, len(goStruct.Fields))

	for _, expr := range renderedSchemaExprs(goStruct) {
		for _, ref := range referencedSchemaNames(expr) {
			typeName := strings.TrimSuffix(ref, zodSchemaSuffix)
			if seen[typeName] {
				continue
			}
			if _, ok := byName[typeName]; !ok {
				// Refers to a type that is not generated; nothing to order against.
				continue
			}
			// A self-reference is included deliberately: visit sees its own colour
			// as grey and records it as the back edge that becomes a getter.
			seen[typeName] = true
			deps = append(deps, typeName)
		}
	}

	slices.SortStableFunc(deps, func(i, j string) int { return cmp.Compare(i, j) })
	return deps
}

// renderedSchemaExprs returns the zod expressions a struct's schema is built from,
// which is what emission order must be derived from.
func renderedSchemaExprs(goStruct *GoStruct) []string {
	if goStruct.AliasOf != nil && len(goStruct.AliasOf.DeclaredValues) > 0 {
		// An enum references nothing.
		return nil
	}

	exprs := make([]string, 0, len(goStruct.Fields)+1)
	for _, field := range goStruct.Fields {
		if field.JsonName == "" {
			continue
		}
		exprs = append(exprs, fieldSchema(field))
	}
	if len(goStruct.Fields) == 0 && goStruct.AliasOf != nil {
		exprs = append(exprs, tsTypeToZod(goStruct.AliasOf.TypescriptType))
	}
	return exprs
}
