"""AniList media-tag catalog for the advanced-search tag filter.

Ported from the web frontend's ADVANCED_SEARCH_MEDIA_TAGS. Each entry is a
``(name, category, is_adult)`` triple used to build the grouped tag picker;
adult-flagged tags are only offered when the server enables adult content.
"""

from __future__ import annotations

# (name, category, is_adult)
MEDIA_TAGS: list[tuple[str, str, bool]] = [
    ("4-koma", "Technical", False),
    ("Achromatic", "Technical", False),
    ("Achronological Order", "Setting-Time", False),
    ("Acrobatics", "Theme-Game-Sport", False),
    ("Acting", "Theme-Arts", False),
    ("Adoption", "Theme-Other", False),
    ("Advertisement", "Technical", False),
    ("Afterlife", "Setting-Universe", False),
    ("Age Gap", "Theme-Romance", False),
    ("Age Regression", "Cast-Traits", False),
    ("Agender", "Cast-Traits", False),
    ("Agriculture", "Theme-Slice of Life", False),
    ("Ahegao", "Sexual Content", True),
    ("Airsoft", "Theme-Game-Sport", False),
    ("Alchemy", "Theme-Fantasy", False),
    ("Aliens", "Cast-Traits", False),
    ("Alternate Universe", "Setting-Universe", False),
    ("American Football", "Theme-Game-Sport", False),
    ("Amnesia", "Cast-Traits", False),
    ("Amputation", "Sexual Content", True),
    ("Anachronism", "Setting-Time", False),
    ("Anal Sex", "Sexual Content", True),
    ("Ancient China", "Setting-Time", False),
    ("Angels", "Cast-Traits", False),
    ("Animals", "Theme-Other", False),
    ("Anthology", "Technical", False),
    ("Anthropomorphism", "Cast-Traits", False),
    ("Anti-Hero", "Cast-Main Cast", False),
    ("Archery", "Theme-Action", False),
    ("Armpits", "Sexual Content", True),
    ("Aromantic", "Cast-Traits", False),
    ("Arranged Marriage", "Cast-Traits", False),
    ("Artificial Intelligence", "Cast-Traits", False),
    ("Asexual", "Cast-Traits", False),
    ("Ashikoki", "Sexual Content", True),
    ("Asphyxiation", "Sexual Content", True),
    ("Assassins", "Theme-Other-Organisations", False),
    ("Astronomy", "Theme-Other", False),
    ("Athletics", "Theme-Game-Sport", False),
    ("Augmented Reality", "Setting-Universe", False),
    ("Autobiographical", "Theme-Other", False),
    ("Aviation", "Theme-Other-Vehicle", False),
    ("Badminton", "Theme-Game-Sport", False),
    ("Ballet", "Theme-Arts", False),
    ("Band", "Theme-Arts-Music", False),
    ("Bar", "Setting-Scene", False),
    ("Baseball", "Theme-Game-Sport", False),
    ("Basketball", "Theme-Game-Sport", False),
    ("Battle Royale", "Theme-Action", False),
    ("Biographical", "Theme-Other", False),
    ("Bisexual", "Cast-Traits", False),
    ("Blackmail", "Theme-Other", False),
    ("Board Game", "Theme-Game", False),
    ("Boarding School", "Setting-Scene", False),
    ("Body Horror", "Theme-Other", False),
    ("Body Image", "Theme-Other", False),
    ("Body Swapping", "Theme-Fantasy", False),
    ("Bondage", "Sexual Content", True),
    ("Boobjob", "Sexual Content", True),
    ("Bowling", "Theme-Game-Sport", False),
    ("Boxing", "Theme-Game-Sport", False),
    ("Boys' Love", "Theme-Romance", False),
    ("Bullying", "Theme-Drama", False),
    ("Butler", "Cast-Traits", False),
    ("Calligraphy", "Theme-Arts", False),
    ("Camping", "Setting-Scene", False),
    ("Cannibalism", "Theme-Other", False),
    ("Card Battle", "Theme-Game-Card & Board Game", False),
    ("Cars", "Theme-Other-Vehicle", False),
    ("Centaur", "Cast-Traits", False),
    ("Cervix Penetration", "Sexual Content", True),
    ("CGI", "Technical", False),
    ("Cheating", "Sexual Content", True),
    ("Cheerleading", "Theme-Game-Sport", False),
    ("Chibi", "Theme-Other", False),
    ("Chimera", "Cast-Traits", False),
    ("Chuunibyou", "Cast-Traits", False),
    ("Circus", "Setting-Scene", False),
    ("Class Struggle", "Theme-Drama", False),
    ("Classic Literature", "Theme-Arts", False),
    ("Classical Music", "Theme-Arts-Music", False),
    ("Clone", "Cast-Traits", False),
    ("Coastal", "Setting-Scene", False),
    ("Cohabitation", "Theme-Romance", False),
    ("College", "Setting-Scene", False),
    ("Coming of Age", "Theme-Drama", False),
    ("Conspiracy", "Theme-Drama", False),
    ("Cosmic Horror", "Theme-Other", False),
    ("Cosplay", "Cast-Traits", False),
    ("Cowboys", "Cast-Traits", False),
    ("Creature Taming", "Theme-Other", False),
    ("Crime", "Theme-Other", False),
    ("Criminal Organization", "Theme-Other-Organisations", False),
    ("Crossdressing", "Cast-Traits", False),
    ("Crossover", "Theme-Other", False),
    ("Cult", "Theme-Other-Organisations", False),
    ("Cultivation", "Theme-Fantasy", False),
    ("Cumflation", "Sexual Content", True),
    ("Cunnilingus", "Sexual Content", True),
    ("Curses", "Theme-Fantasy", False),
    ("Cute Boys Doing Cute Things", "Theme-Slice of Life", False),
    ("Cute Girls Doing Cute Things", "Theme-Slice of Life", False),
    ("Cyberpunk", "Theme-Sci-Fi", False),
    ("Cyborg", "Cast-Traits", False),
    ("Cycling", "Theme-Game-Sport", False),
    ("Dancing", "Theme-Arts-Music", False),
    ("Death Game", "Theme-Other", False),
    ("Deepthroat", "Sexual Content", True),
    ("Defloration", "Sexual Content", True),
    ("Delinquents", "Cast-Traits", False),
    ("Demons", "Cast-Traits", False),
    ("Denpa", "Theme-Other", False),
    ("Desert", "Setting-Scene", False),
    ("Detective", "Cast-Traits", False),
    ("DILF", "Sexual Content", True),
    ("Dinosaurs", "Cast-Traits", False),
    ("Disability", "Cast-Traits", False),
    ("Dissociative Identities", "Cast-Traits", False),
    ("Double Penetration", "Sexual Content", True),
    ("Dragons", "Cast-Traits", False),
    ("Drawing", "Theme-Arts", False),
    ("Drugs", "Theme-Other", False),
    ("Dullahan", "Cast-Traits", False),
    ("Dungeon", "Setting-Scene", False),
    ("Dystopian", "Setting-Time", False),
    ("E-Sports", "Theme-Game", False),
    ("Eco-Horror", "Theme-Drama", False),
    ("Economics", "Theme-Other", False),
    ("Educational", "Theme-Other", False),
    ("Elderly Protagonist", "Cast-Main Cast", False),
    ("Elf", "Cast-Traits", False),
    ("Ensemble Cast", "Cast-Main Cast", False),
    ("Environmental", "Theme-Other", False),
    ("Episodic", "Technical", False),
    ("Ero Guro", "Theme-Other", False),
    ("Erotic Piercings", "Sexual Content", True),
    ("Espionage", "Theme-Action", False),
    ("Estranged Family", "Cast-Main Cast", False),
    ("Exhibitionism", "Sexual Content", True),
    ("Exorcism", "Theme-Fantasy", False),
    ("Facial", "Sexual Content", True),
    ("Fairy", "Cast-Traits", False),
    ("Fairy Tale", "Theme-Fantasy", False),
    ("Fake Relationship", "Theme-Drama", False),
    ("Family Life", "Theme-Slice of Life", False),
    ("Fashion", "Theme-Arts", False),
    ("Feet", "Sexual Content", True),
    ("Fellatio", "Sexual Content", True),
    ("Female Harem", "Theme-Romance", False),
    ("Female Protagonist", "Cast-Main Cast", False),
    ("Femboy", "Cast-Traits", False),
    ("Femdom", "Sexual Content", True),
    ("Fencing", "Theme-Game-Sport", False),
    ("Filmmaking", "Theme-Other", False),
    ("Fingering", "Sexual Content", True),
    ("Firefighters", "Theme-Other-Organisations", False),
    ("Fishing", "Theme-Game-Sport", False),
    ("Fisting", "Sexual Content", True),
    ("Fitness", "Theme-Game-Sport", False),
    ("Flash", "Technical", False),
    ("Flat Chest", "Sexual Content", True),
    ("Food", "Theme-Arts", False),
    ("Football", "Theme-Game-Sport", False),
    ("Foreign", "Setting-Scene", False),
    ("Found Family", "Theme-Other", False),
    ("Fugitive", "Theme-Action", False),
    ("Full CGI", "Technical", False),
    ("Full Color", "Technical", False),
    ("Futanari", "Sexual Content", True),
    ("Gambling", "Theme-Other", False),
    ("Gangs", "Theme-Other-Organisations", False),
    ("Gender Bending", "Theme-Other", False),
    ("Ghost", "Cast-Traits", False),
    ("Go", "Theme-Game-Card & Board Game", False),
    ("Goblin", "Cast-Traits", False),
    ("Gods", "Cast-Traits", False),
    ("Golf", "Theme-Game-Sport", False),
    ("Gore", "Theme-Other", False),
    ("Group Sex", "Sexual Content", True),
    ("Guns", "Theme-Action", False),
    ("Gyaru", "Cast-Traits", False),
    ("Hair Pulling", "Sexual Content", True),
    ("Handball", "Theme-Game-Sport", False),
    ("Handjob", "Sexual Content", True),
    ("Henshin", "Theme-Fantasy", False),
    ("Heterosexual", "Theme-Romance", False),
    ("Hikikomori", "Cast-Traits", False),
    ("Hip-hop Music", "Theme-Arts-Music", False),
    ("Historical", "Setting-Time", False),
    ("Homeless", "Cast-Traits", False),
    ("Horticulture", "Theme-Slice of Life", False),
    ("Human Pet", "Sexual Content", True),
    ("Hypersexuality", "Sexual Content", True),
    ("Ice Skating", "Theme-Game-Sport", False),
    ("Idol", "Cast-Traits", False),
    ("Incest", "Sexual Content", True),
    ("Indigenous Cultures", "Theme-Other", False),
    ("Inn", "Setting-Scene", False),
    ("Inseki", "Sexual Content", True),
    ("Irrumatio", "Sexual Content", True),
    ("Isekai", "Theme-Fantasy", False),
    ("Iyashikei", "Theme-Slice of Life", False),
    ("Jazz Music", "Theme-Arts-Music", False),
    ("Josei", "Demographic", False),
    ("Judo", "Theme-Game-Sport", False),
    ("Kabuki", "Theme-Arts", False),
    ("Kaiju", "Theme-Fantasy", False),
    ("Karuta", "Theme-Game-Card & Board Game", False),
    ("Kemonomimi", "Cast-Traits", False),
    ("Kids", "Demographic", False),
    ("Kingdom Management", "Theme-Drama", False),
    ("Konbini", "Setting-Scene", False),
    ("Kuudere", "Cast-Traits", False),
    ("Lacrosse", "Theme-Game-Sport", False),
    ("Lactation", "Sexual Content", True),
    ("Language Barrier", "Theme-Other", False),
    ("Large Breasts", "Sexual Content", True),
    ("LGBTQ+ Themes", "Theme-Other", False),
    ("Long Strip", "Technical", False),
    ("Lost Civilization", "Theme-Other", False),
    ("Love Triangle", "Theme-Romance", False),
    ("Mafia", "Theme-Other-Organisations", False),
    ("Magic", "Theme-Fantasy", False),
    ("Mahjong", "Theme-Game-Card & Board Game", False),
    ("Maids", "Cast-Traits", False),
    ("Makeup", "Theme-Arts", False),
    ("Male Harem", "Theme-Romance", False),
    ("Male Pregnancy", "Sexual Content", True),
    ("Male Protagonist", "Cast-Main Cast", False),
    ("Manzai", "Theme-Arts", False),
    ("Marriage", "Theme-Other", False),
    ("Martial Arts", "Theme-Action", False),
    ("Masochism", "Sexual Content", True),
    ("Masturbation", "Sexual Content", True),
    ("Matchmaking", "Theme-Romance", False),
    ("Mating Press", "Sexual Content", True),
    ("Matriarchy", "Setting", False),
    ("Medicine", "Theme-Other", False),
    ("Medieval", "Setting-Time", False),
    ("Memory Manipulation", "Theme-Other", False),
    ("Mermaid", "Cast-Traits", False),
    ("Meta", "Theme-Other", False),
    ("Metal Music", "Theme-Arts-Music", False),
    ("MILF", "Sexual Content", True),
    ("Military", "Theme-Other-Organisations", False),
    ("Mixed Gender Harem", "Theme-Romance", False),
    ("Mixed Media", "Technical", False),
    ("Modeling", "Theme-Arts", False),
    ("Monster Boy", "Cast-Traits", False),
    ("Monster Girl", "Cast-Traits", False),
    ("Mopeds", "Theme-Other-Vehicle", False),
    ("Motorcycles", "Theme-Other-Vehicle", False),
    ("Mountaineering", "Theme-Other", False),
    ("Musical Theater", "Theme-Arts-Music", False),
    ("Mythology", "Theme-Fantasy", False),
    ("Nakadashi", "Sexual Content", True),
    ("Natural Disaster", "Setting-Scene", False),
    ("Necromancy", "Theme-Fantasy", False),
    ("Nekomimi", "Cast-Traits", False),
    ("Netorare", "Sexual Content", True),
    ("Netorase", "Sexual Content", True),
    ("Netori", "Sexual Content", True),
    ("Ninja", "Cast-Traits", False),
    ("No Dialogue", "Technical", False),
    ("Noir", "Theme-Other", False),
    ("Non-fiction", "Technical", False),
    ("Nudity", "Cast-Traits", False),
    ("Nun", "Cast-Traits", False),
    ("Office", "Setting-Scene", False),
    ("Office Lady", "Cast-Traits", False),
    ("Oiran", "Cast-Traits", False),
    ("Ojou-sama", "Cast-Traits", False),
    ("Omegaverse", "Setting-Universe", True),
    ("Orphan", "Cast-Traits", False),
    ("Otaku Culture", "Theme-Other", False),
    ("Outdoor Activities", "Setting-Scene", False),
    ("Oyakodon", "Sexual Content", True),
    ("Pandemic", "Theme-Other", False),
    ("Parenthood", "Theme-Slice of Life", False),
    ("Parkour", "Theme-Game-Sport", False),
    ("Parody", "Theme-Comedy", False),
    ("Pet Play", "Sexual Content", True),
    ("Philosophy", "Theme-Other", False),
    ("Photography", "Theme-Arts", False),
    ("Pirates", "Cast-Traits", False),
    ("Poker", "Theme-Game-Card & Board Game", False),
    ("Police", "Theme-Other-Organisations", False),
    ("Politics", "Theme-Other", False),
    ("Polyamorous", "Theme-Romance", False),
    ("Post-Apocalyptic", "Setting-Universe", False),
    ("POV", "Technical", False),
    ("Pregnancy", "Theme-Other", False),
    ("Primarily Adult Cast", "Cast-Main Cast", False),
    ("Primarily Animal Cast", "Cast-Main Cast", False),
    ("Primarily Child Cast", "Cast-Main Cast", False),
    ("Primarily Female Cast", "Cast-Main Cast", False),
    ("Primarily Male Cast", "Cast-Main Cast", False),
    ("Primarily Teen Cast", "Cast-Main Cast", False),
    ("Prison", "Setting-Scene", False),
    ("Prostitution", "Sexual Content", True),
    ("Proxy Battle", "Theme-Other", False),
    ("Psychosexual", "Theme-Other", False),
    ("Public Sex", "Sexual Content", True),
    ("Puppetry", "Technical", False),
    ("Rakugo", "Theme-Arts", False),
    ("Rape", "Sexual Content", True),
    ("Real Robot", "Theme-Sci-Fi-Mecha", False),
    ("Rehabilitation", "Theme-Drama", False),
    ("Reincarnation", "Theme-Other", False),
    ("Religion", "Theme-Other", False),
    ("Rescue", "Theme-Other", False),
    ("Restaurant", "Setting-Scene", False),
    ("Revenge", "Theme-Drama", False),
    ("Reverse Isekai", "Theme-Fantasy", False),
    ("Rimjob", "Sexual Content", True),
    ("Robots", "Cast-Traits", False),
    ("Rock Music", "Theme-Arts-Music", False),
    ("Rotoscoping", "Technical", False),
    ("Royal Affairs", "Theme-Other", False),
    ("Rugby", "Theme-Game-Sport", False),
    ("Rural", "Setting-Scene", False),
    ("Sadism", "Sexual Content", True),
    ("Samurai", "Cast-Traits", False),
    ("Satire", "Theme-Comedy", False),
    ("Scat", "Sexual Content", True),
    ("School", "Setting-Scene", False),
    ("School Club", "Setting-Scene", False),
    ("Scissoring", "Sexual Content", True),
    ("Scuba Diving", "Theme-Game-Sport", False),
    ("Seinen", "Demographic", False),
    ("Sex Toys", "Sexual Content", True),
    ("Shapeshifting", "Theme-Fantasy", False),
    ("Shimaidon", "Sexual Content", True),
    ("Ships", "Theme-Other-Vehicle", False),
    ("Shogi", "Theme-Game-Card & Board Game", False),
    ("Shoujo", "Demographic", False),
    ("Shounen", "Demographic", False),
    ("Shrine Maiden", "Cast-Traits", False),
    ("Skateboarding", "Theme-Game-Sport", False),
    ("Skeleton", "Cast-Traits", False),
    ("Slapstick", "Theme-Comedy", False),
    ("Slavery", "Theme-Other", False),
    ("Snowscape", "Setting-Scene", False),
    ("Software Development", "Theme-Other", False),
    ("Space", "Setting-Universe", False),
    ("Space Opera", "Theme-Sci-Fi", False),
    ("Spearplay", "Theme-Action", False),
    ("Squirting", "Sexual Content", True),
    ("Steampunk", "Theme-Fantasy", False),
    ("Stop Motion", "Technical", False),
    ("Succubus", "Cast-Traits", False),
    ("Suicide", "Theme-Drama", False),
    ("Sumata", "Sexual Content", True),
    ("Sumo", "Theme-Game-Sport", False),
    ("Super Power", "Theme-Fantasy", False),
    ("Super Robot", "Theme-Sci-Fi-Mecha", False),
    ("Superhero", "Theme-Fantasy", False),
    ("Surfing", "Theme-Game-Sport", False),
    ("Surreal Comedy", "Theme-Comedy", False),
    ("Survival", "Theme-Other", False),
    ("Swapping", "Sexual Content", True),
    ("Sweat", "Sexual Content", True),
    ("Swimming", "Theme-Game-Sport", False),
    ("Swordplay", "Theme-Action", False),
    ("Table Tennis", "Theme-Game-Sport", False),
    ("Tanks", "Theme-Other-Vehicle", False),
    ("Tanned Skin", "Cast-Traits", False),
    ("Teacher", "Cast-Traits", False),
    ("Teens' Love", "Theme-Romance", False),
    ("Tennis", "Theme-Game-Sport", False),
    ("Tentacles", "Sexual Content", True),
    ("Terrorism", "Theme-Other", False),
    ("Threesome", "Sexual Content", True),
    ("Time Loop", "Theme-Sci-Fi", False),
    ("Time Manipulation", "Theme-Sci-Fi", False),
    ("Time Skip", "Setting-Time", False),
    ("Tokusatsu", "Theme-Sci-Fi", False),
    ("Tomboy", "Cast-Traits", False),
    ("Torture", "Theme-Other", False),
    ("Tragedy", "Theme-Drama", False),
    ("Trains", "Theme-Other-Vehicle", False),
    ("Transgender", "Cast-Traits", False),
    ("Travel", "Theme-Other", False),
    ("Triads", "Theme-Other-Organisations", False),
    ("Tsundere", "Cast-Traits", False),
    ("Twins", "Cast-Traits", False),
    ("Unrequited Love", "Theme-Romance", False),
    ("Urban", "Setting-Scene", False),
    ("Urban Fantasy", "Setting-Universe", False),
    ("Vampire", "Cast-Traits", False),
    ("Vertical Video", "Technical", False),
    ("Veterinarian", "Cast-Traits", False),
    ("Video Games", "Theme-Game", False),
    ("Vikings", "Cast-Traits", False),
    ("Villainess", "Cast-Traits", False),
    ("Virginity", "Sexual Content", True),
    ("Virtual World", "Setting-Universe", False),
    ("Vocal Synth", "Theme-Other", False),
    ("Volleyball", "Theme-Game-Sport", False),
    ("Vore", "Sexual Content", True),
    ("Voyeur", "Sexual Content", True),
    ("VTuber", "Cast-Traits", False),
    ("War", "Theme-Other", False),
    ("Watersports", "Sexual Content", True),
    ("Werewolf", "Cast-Traits", False),
    ("Wilderness", "Setting-Scene", False),
    ("Witch", "Cast-Traits", False),
    ("Work", "Setting-Scene", False),
    ("Wrestling", "Theme-Game-Sport", False),
    ("Writing", "Theme-Arts", False),
    ("Wuxia", "Theme-Fantasy", False),
    ("Yakuza", "Theme-Other-Organisations", False),
    ("Yandere", "Cast-Traits", False),
    ("Youkai", "Theme-Fantasy", False),
    ("Yuri", "Theme-Romance", False),
    ("Zombie", "Cast-Traits", False),
    ("Zoophilia", "Sexual Content", True),
]
